version: '3.8'
services:
#  database:
#    container_name: ddang_mysql
#    image: mysql:latest
#    ports:
#      - "3307:3306"
#    environment:
#      MYSQL_DATABASE: ddang
#      MYSQL_USER: ${DB_USER}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#    volumes:
#      - ./mysql/data:/var/lib/mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    container_name: ddang_redis
    image: redis:latest
    ports:
      - '6379:6379'

  application:
    container_name: ddang
    build:
      dockerfile: Dockerfile
    volumes:
      - ./src:/src
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dep
#      SPRING_DATASOURCE_URL: jdbc:mysql://ddang_mysql:3306/ddang
#      SPRING_DATASOURCE_USERNAME: ${DB_USER}
#      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATA_REDIS_HOST: ddang_redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
#      - database
      - zookeeper
      - kafka
      - redis
